### ISSUE TITLE
POI search: Please add aliases (and their translations) for POI tags

### ISSUE THREAD

**Issue by palbr** [rinigus/geocoder-nlp#37]
Searching for POIs can be improved by using aliases for POI tags:

My use case: I wanted search next filling stations around my current position. (My car was low on gas)

In German the appropriate word would be "Tankstelle". This translates to the English words "filling station" or "gas station". But POI searches with both translations failed in PoorMap (+ OSM Scout Server), since the "official" tag name for this kind of infrastructure is "amenity : fuel". (http://wiki.openstreetmap.org/wiki/Map_Features)

Another example: Search for "drugstore" gives no results, since the "official" tag name is "pharmacy".

Possible tag lists:

- http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/EN
- http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/DE
- ...

But I am not sure, whether the "... in" or "... near" variations will help.

Example: The user searches for "Tankstelle", OSM Scout Server detects that this is an alias for a POI tag and adds "amenity_fuel" to the search string.

See also:
https://github.com/otsaloma/poor-maps/issues/59

**Comment by rinigus** [comment]
Thank you, I'll look into it.

**Comment by rinigus** [comment]
This is implemented now as a combination of geocoder and OSM Scout Server. Official tags are at https://rinigus.github.io/osmscout-server/tags/ , linked from the bottom part of https://rinigus.github.io/osmscout-server/en/ and OSM Scout Server README. 

All seems to be working as intended, testing it now before release. Would also have to reimport geocoder data to full support all new tags.

But, as such, this issue is resolved.
